version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=256MB"]
  express-app:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres


volumes:
  postgres_data: